spring.application.name=api-gateway
server.port=8080

# Eureka Config
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Optional: log requests
logging.level.org.springframework.cloud.gateway=DEBUG

# User Profile Route
spring.cloud.gateway.routes[0].id=user-profile-service
spring.cloud.gateway.routes[0].uri=lb://user-profile-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/user-profile/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# Job Recruiter Route
spring.cloud.gateway.routes[1].id=job-recruiter-service
spring.cloud.gateway.routes[1].uri=lb://job-recruiter-service
spring.cloud.gateway.routes[1].predicates[0]=Path=/job-recruiter/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1